spring:
  datasource:
    url: jdbc:h2:mem:farmacia_testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop   # Crea el esquema al inicio y lo destruye al terminar las pruebas
    show-sql: true            # Muestra sentencias SQL en consola
    properties:
      hibernate:
        format_sql: true      # Formatea el SQL en consola

  h2:
    console:
      enabled: true
      path: /h2-console       # Podr√°s abrirlo en http://localhost:8080/h2-console si ejecutas el contexto

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.test: info

# Propiedades de pruebas personalizadas
app:
  nombre: Farmacia - Perfil de Test
  modo: simulacion
